apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    containers:
    - name: nginx
      image: joindevops/deployment:2.0
      ports:
      - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 32000